language: go

go:
  - 1.5
  - 1.6

install:
  - go get -u github.com/golang/lint/golint

script:
  - go test -v
  - test -z "$(golint . | tee /dev/stderr)"
  - test -z "$(gofmt -e -l . | tee /dev/stderr)"
