language: go

go:
  - 1.6
  - 1.7

install:
  - go get -u github.com/golang/lint/golint

script:
  - go test -v ./cmd/itcrowdipsum
  - test -z "$(golint ./cmd/itcrowdipsum | tee /dev/stderr)"
  - test -z "$(gofmt -e -l ./cmd/itcrowdipsum | tee /dev/stderr)"
